### PR TITLE
CURA-5931 Fix the center for subparts

### PR DESCRIPTION
**Pull request by LipuFei**
CURA-5931

### CODE REVIEW

**Comment by fieldOfView** [comment]
Thanks for the PR. Could you elaborate what the problem is that you are fixing? I don't have access to jira, so I can't read the description of CURA-5931

Did you check your fix on objects that are first scaled and/or rotated before they are split apart?

**Comment by fieldOfView** [comment]
Correct me if I am wrong, but this fix makes it impossible to merge the submodels back together, doesn't it?

**Comment by LipuFei** [comment]
If you install the god mode plugin (https://github.com/sedwards2009/cura-god-mode-plugin), you can switch to God View and see that the subparts have their centers at the original object's center.

image

The fix I made is for each subpart, change the center of the object to the center of itself using the bounding box, and then apply the transformation. I'm not sure if it has other problems, but I can still merge them back by using CTRL-Z or Merge objects.

**Comment by LipuFei** [comment]
I just found that this change works for the objects model made by Diego, but it still has problems with the hex tiles model.

**Comment by Ghostkeeper** [comment]
> I don't have access to jira, so I can't read the description of CURA-5931

The description of that ticket says:

> GitHub issue: https://github.com/Ultimaker/Cura/issues/4767

**Comment by fieldOfView** [comment]
I don't think this PR is the correct way to solve the issue in https://github.com/Ultimaker/Cura/issues/4767.

The plugin keeps the original origin so that the user can "explode" a single STL into subparts, change properties on select subparts (such as extruder) and then allow them to merge the subparts back in their original relation to eachother.

This comment clearly explains what Cura does wrong: https://github.com/Ultimaker/Cura/issues/4767#issuecomment-465027105
Trying to fix that here by breaking functionality does not make sense to me.

AFAIK, the idea of saving a project is to save the state of the application so you can continue from the same state. Something that is not an issue before saving a project should not be an issue after saving the project.

**Comment by fieldOfView** [comment]
I have closed the PR, but feel free to make your case to why you think this should be fixed here instead of in Cura. As far as I am concerned, the plugin does nothing wrong here.

**Pull request closed without merging**
